# Generated by Django 2.0.7 on 2018-07-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbboarlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbboarlog',
        ),
    ]
