# Generated by Django 2.0.7 on 2018-07-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbboarlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbboarlog',
        ),
    ]
