# Generated by Django 2.0.7 on 2018-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_tbboarlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbboarlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('compname', models.CharField(max_length=100)),
            ],
        ),
    ]
