# Generated by Django 2.0.7 on 2018-08-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbboarlog',
        ),
        migrations.DeleteModel(
            name='tbcontact',
        ),
        migrations.DeleteModel(
            name='tblogin',
        ),
    ]
