# Generated by Django 2.0.7 on 2018-08-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tbboarlog_tbcontact_tblogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbshoping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cato', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('quty', models.CharField(max_length=100)),
                ('expdate', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
    ]
