# Generated by Django 2.0.7 on 2018-08-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tbnoti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbnoti',
        ),
    ]
