# Generated by Django 2.0.7 on 2018-08-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tbnoti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbnoti',
        ),
    ]
