# Generated by Django 2.0.7 on 2018-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_tbnoti'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbnoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentid', models.IntegerField()),
                ('recid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('mater', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('seend', models.CharField(max_length=100)),
            ],
        ),
    ]
