# Generated by Django 2.0.7 on 2018-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_tbonuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
