# Generated by Django 2.0.7 on 2018-09-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tbcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbcato',
        ),
    ]
