# Generated by Django 2.0.7 on 2018-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_tbcato'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbmycato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cato', models.CharField(max_length=100)),
            ],
        ),
    ]
