# Generated by Django 2.0.7 on 2018-09-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_tbpetcato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbpetcato',
        ),
    ]
