# Generated by Django 2.0.7 on 2018-09-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_tbpets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbpets',
        ),
    ]
