# Generated by Django 2.0.7 on 2018-09-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_tbpets'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbpets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cato', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('doc', models.ImageField(blank=True, null=True, upload_to='Images/petdocs', verbose_name='file')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Images/pets', verbose_name='file')),
            ],
        ),
    ]
