# Generated by Django 2.0.7 on 2018-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_tbpets'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
    ]
