# Generated by Django 2.0.7 on 2018-09-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_tbpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbpayment',
        ),
    ]
