# Generated by Django 2.0.7 on 2018-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_delete_tbatm'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbatm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atmno', models.CharField(max_length=14)),
                ('amt', models.CharField(max_length=15)),
                ('expm', models.CharField(max_length=2)),
                ('expy', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
