# Generated by Django 2.0.7 on 2018-09-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_tbatm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbatm',
        ),
        migrations.DeleteModel(
            name='tbboarlog',
        ),
        migrations.DeleteModel(
            name='tbcart',
        ),
        migrations.DeleteModel(
            name='tbcontact',
        ),
        migrations.DeleteModel(
            name='tblogin',
        ),
        migrations.DeleteModel(
            name='tbmycato',
        ),
        migrations.DeleteModel(
            name='tbnoti',
        ),
        migrations.DeleteModel(
            name='tbonuser',
        ),
        migrations.DeleteModel(
            name='tbpayment',
        ),
        migrations.DeleteModel(
            name='tbpetcato',
        ),
        migrations.DeleteModel(
            name='tbpets',
        ),
        migrations.DeleteModel(
            name='tbshoping',
        ),
    ]
