# Generated by Django 2.0.7 on 2018-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0045_auto_20180914_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbatm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atmno', models.CharField(max_length=14)),
                ('amt', models.CharField(max_length=15)),
                ('expm', models.CharField(max_length=2)),
                ('expy', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tbboarlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('approve', models.CharField(max_length=100)),
                ('compname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bandc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tblogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbmycato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbnoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentid', models.IntegerField()),
                ('recid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('mater', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('seend', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbonuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersid', models.IntegerField()),
                ('varid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('petid', models.IntegerField()),
                ('repdate', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=50000)),
                ('desclastupdate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbpetcato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cato', models.CharField(max_length=100)),
                ('petcatoimg', models.ImageField(blank=True, null=True, upload_to='Images/pettype', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='tbpets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cato', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('Vdate', models.CharField(max_length=100)),
                ('doc', models.ImageField(blank=True, null=True, upload_to='Images/petdocs', verbose_name='file')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Images/pets', verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='tbshoping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cato', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('quty', models.CharField(max_length=100)),
                ('expdate', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbvacc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petid', models.CharField(max_length=14)),
                ('vacdate', models.CharField(max_length=100)),
                ('vacc', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
