# Generated by Django 2.0.7 on 2018-09-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_tbatm_tbboarlog_tbcart_tbcontact_tblogin_tbmycato_tbnoti_tbonuser_tbpayment_tbpetcato_tbpets_tbshopi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbcart',
        ),
    ]
