# Generated by Django 2.0.7 on 2018-09-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_tbcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbnoti',
        ),
    ]
