# Generated by Django 2.0.7 on 2018-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_tbnoti'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbhandlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tlicence', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('assigments', models.CharField(max_length=100)),
                ('dogid', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=100)),
            ],
        ),
    ]
