# Generated by Django 2.0.7 on 2018-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20180921_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('sendid', models.IntegerField()),
                ('resvid', models.IntegerField()),
            ],
        ),
    ]
