# Generated by Django 2.0.7 on 2018-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_tbchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbchat',
        ),
    ]
