# Generated by Django 2.0.7 on 2018-09-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_tbchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbonuser',
        ),
    ]
