# Generated by Django 2.0.7 on 2018-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_delete_tbonuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbonuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersid', models.IntegerField()),
                ('varid', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('petid', models.IntegerField()),
                ('repdate', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=50000)),
                ('desclastupdate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('useracc', models.CharField(max_length=100)),
                ('dateuseracc', models.CharField(max_length=100)),
            ],
        ),
    ]
