# Generated by Django 2.0.7 on 2018-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_tbonuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbmedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendid', models.IntegerField()),
                ('recvid', models.IntegerField()),
                ('vidimg', models.CharField(max_length=100)),
                ('media', models.ImageField(blank=True, null=True, upload_to='Images/licence', verbose_name='file')),
            ],
        ),
    ]
