# Generated by Django 2.0.7 on 2018-09-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_tbbandtpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbboarlog',
        ),
    ]
