# Generated by Django 2.0.7 on 2018-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_delete_tbboarlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbboarlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('propic', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('approve', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('compname', models.CharField(max_length=100)),
                ('licno', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
