# Generated by Django 2.0.7 on 2018-09-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_tbboarlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbatm',
        ),
        migrations.DeleteModel(
            name='tbBandTpay',
        ),
        migrations.DeleteModel(
            name='tbcart',
        ),
        migrations.DeleteModel(
            name='tbchat',
        ),
        migrations.DeleteModel(
            name='tbhandlers',
        ),
        migrations.DeleteModel(
            name='tbmedia',
        ),
        migrations.DeleteModel(
            name='tbmycato',
        ),
        migrations.DeleteModel(
            name='tbnoti',
        ),
        migrations.DeleteModel(
            name='tbonuser',
        ),
        migrations.DeleteModel(
            name='tbpayment',
        ),
        migrations.DeleteModel(
            name='tbpetcato',
        ),
        migrations.DeleteModel(
            name='tbpets',
        ),
        migrations.DeleteModel(
            name='tbvacc',
        ),
    ]
