# Generated by Django 2.0.7 on 2018-09-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_tbatm_tbbandtpay_tbcart_tbchat_tbhandlers_tbmedia_tbmycato_tbnoti_tbonuser_tbpayment_tbpetcato_tbpet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbboarlog',
        ),
    ]
