# Generated by Django 2.0.7 on 2018-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_delete_tbbandtpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbBandTpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisid', models.IntegerField()),
                ('fromdate', models.CharField(max_length=100)),
                ('todate', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('paymentid', models.IntegerField()),
            ],
        ),
    ]
