# Generated by Django 2.0.7 on 2018-09-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_tbpets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbpets',
        ),
    ]
