# Generated by Django 2.1.3 on 2018-11-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_tbfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbnotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Images/licence', verbose_name='file')),
            ],
        ),
    ]
