# Generated by Django 2.1.3 on 2018-11-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_tbnotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbonuser',
        ),
    ]
