# Generated by Django 2.1.3 on 2018-11-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_tbamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbamount',
        ),
    ]
