# Generated by Django 2.1.3 on 2018-11-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_tbamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chart',
        ),
    ]
