# Generated by Django 2.1.3 on 2018-11-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='media',
        ),
    ]
