# Generated by Django 2.1.3 on 2018-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_delete_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addid', models.IntegerField()),
                ('vidimg', models.CharField(max_length=100)),
                ('media', models.ImageField(blank=True, null=True, upload_to='Images/licence', verbose_name='file')),
            ],
        ),
    ]
