# Generated by Django 2.1.3 on 2018-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthpayuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('recid', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
