# Generated by Django 2.0.6 on 2019-01-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_monthpayuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbbandtpay',
            name='paymentid',
            field=models.IntegerField(null=True),
        ),
    ]
