# Generated by Django 2.0.6 on 2019-01-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_remove_tbpets_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhandlers',
            name='tlicence',
        ),
    ]
