# Generated by Django 2.0.6 on 2019-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_remove_tbhandlers_tlicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='petid',
            field=models.IntegerField(null=True),
        ),
    ]
