# Generated by Django 2.0.6 on 2019-01-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20190104_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbpets',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
